### ISSUE TITLE
Align headset insert in all Z Drives

### ISSUE THREAD

**Issue by Finn2708** [hartk1213/Micron#15]
-This serves as a reminder to myself-

Already fixed here:
![image](https://user-images.githubusercontent.com/58212604/132727221-0ec3f6e6-1731-4c61-ae49-35ccff69ddb3.png)

**Comment by hartk1213** [comment]
awesome, also i just realized there is a heatset and an m3 in the z drive cap for the rubber foot...those can also be removed since they are now m5 and hex nut

**Comment by Finn2708** [comment]
Alright, I will remove them. 
Those were not in the BOM anyway.
